### PR TITLE
Migration from internal repo to public one

### PR DESCRIPTION
**Pull request by Dmitry-Erokhin**
Transferring all files as-is from the tip of the original master branch.
Original Git commit history is not preserved for the security reasons.

### CODE REVIEW

**Comment by Dmitry-Erokhin** [comment]
Checking if self-approvals are disabled...

**Comment by Dmitry-Erokhin** [comment]
👍

**Comment by Dmitry-Erokhin** [comment]
Indeed.

**Comment by dstockhammer** [comment]
:+1:

**Pull request merged**
